version: '3.9'

services:
  eureka-server:
    build:
      context: ./eureka-server
    container_name: eureka-server
    ports:
      - "8081:8081"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka/
      SPRING_PROFILES_ACTIVE: production
    networks:
      - app-network
    restart: unless-stopped

  api-gateway:
    build:
      context: ./api-gateway
    container_name: api-gateway
    ports:
      - "8082:8082"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka/
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - app-network

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./monitoring/grafana/datasource/datasource.yml:/etc/grafana/provisioning/datasource/datasource.yaml
    networks:
      - app-network

  passenger-service:
    build:
      context: ./passenger-service
    container_name: passenger-service
    ports:
      - "8083:8083"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka/
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_DATASOURCE_URL: jdbc:postgresql://passenger-db:5432/passenger_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - app-network

  passenger-db:
    image: postgres:15
    container_name: passenger-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: passenger_db
    volumes:
      - passenger-data:/var/lib/postgresql/data
    networks:
      - app-network

  driver-service:
    build:
      context: ./driver-service
    container_name: driver-service
    ports:
      - "8084:8084"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka/
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_DATASOURCE_URL: jdbc:postgresql://driver-db:5432/driver_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - app-network

  driver-db:
    image: postgres:15
    container_name: driver-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: driver_db
    volumes:
      - driver-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  ride-service:
    build:
      context: ./ride-service
    container_name: ride-service
    ports:
      - "8085:8085"
    env_file:
      - .env
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka/
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_DATASOURCE_URL: jdbc:postgresql://ride-db:5432/ride_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - app-network

  ride-db:
    image: postgres:15
    container_name: ride-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ride_db
    volumes:
      - ride-data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

  rating-service:
    build:
      context: ./rating-service
    container_name: rating-service
    ports:
      - "8086:8086"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8081/eureka/
      SPRING_SLEUTH_SAMPLER_PROBABILITY: "1.0"
      SPRING_DATASOURCE_URL: jdbc:postgresql://rating-db:5432/rating_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
    networks:
      - app-network

  rating-db:
    image: postgres:15
    container_name: rating-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rating_db
    volumes:
      - rating-data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    networks:
      - app-network

volumes:
  grafana-storage:
  passenger-data:
  driver-data:
  ride-data:
  rating-data:

networks:
  app-network:
    driver: bridge
