global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'api-gateway:8082'
          - 'passenger-service:8083'
          - 'driver-service:8084'
          - 'ride-service:8085'
          - 'rating-service:8086'